name: dorm_chef
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  android_intent_plus: ^5.3.1
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  google_sign_in: ^7.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  lottie: ^3.3.1
  mobile_scanner: ^7.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/recipes.json
    - asset/lottie/
