// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMMeuP4tkyrOMgvHevcyLmDoQbcJp4Y9U',
    appId: '1:318643443437:web:6931010ed37adca1415ee4',
    messagingSenderId: '318643443437',
    projectId: 'dorm-chef-8bb66',
    authDomain: 'dorm-chef-8bb66.firebaseapp.com',
    storageBucket: 'dorm-chef-8bb66.firebasestorage.app',
    measurementId: 'G-42L89K280F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkqjqgRmOwXbZ8pW_TvZ7iV-MhFSFHA3o',
    appId: '1:318643443437:android:3eaa77068f7af30d415ee4',
    messagingSenderId: '318643443437',
    projectId: 'dorm-chef-8bb66',
    storageBucket: 'dorm-chef-8bb66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC74sbjTfGHPHHEEP50VecGWXWpbkmI8T0',
    appId: '1:318643443437:ios:06e20d98532b4d12415ee4',
    messagingSenderId: '318643443437',
    projectId: 'dorm-chef-8bb66',
    storageBucket: 'dorm-chef-8bb66.firebasestorage.app',
    iosBundleId: 'com.example.dormChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC74sbjTfGHPHHEEP50VecGWXWpbkmI8T0',
    appId: '1:318643443437:ios:06e20d98532b4d12415ee4',
    messagingSenderId: '318643443437',
    projectId: 'dorm-chef-8bb66',
    storageBucket: 'dorm-chef-8bb66.firebasestorage.app',
    iosBundleId: 'com.example.dormChef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMMeuP4tkyrOMgvHevcyLmDoQbcJp4Y9U',
    appId: '1:318643443437:web:3c3e471cfc95cbc8415ee4',
    messagingSenderId: '318643443437',
    projectId: 'dorm-chef-8bb66',
    authDomain: 'dorm-chef-8bb66.firebaseapp.com',
    storageBucket: 'dorm-chef-8bb66.firebasestorage.app',
    measurementId: 'G-4NNDN090F8',
  );
}
